package expr

func Templates() [][]Object {
	return [][]Object{
		{
			Object{Operand, ""},
			Object{Operator, ""},
			Object{Operand, ""},
		},
		{
			Object{Operand, ""},
			Object{Operator, ""},
			Object{LBrac, "("},
			Object{Operand, ""},
			Object{Operator, ""},
			Object{Operand, ""},
			Object{RBrac, ")"},
		},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
	},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{Operand, ""},
	},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{Operand, ""},
	},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{Operand, ""},
	},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{Operand, ""},
	},
	{
		Object{Operand, ""},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{LBrac, "("},
		Object{Operand, ""},
		Object{Operator, ""},
		Object{Operand, ""},
		Object{RBrac, ")"},
		Object{Operator, ""},
		Object{Operand, ""},
	},
  }
}
